
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: sagar
    password: sagar123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


jwt:
  secret: "dsfknfdslkndslfndsfdsfmfdsnmfdsnfdsnmfdsmdsfnm"